# Generated by Django 5.1.1 on 2024-09-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Portero', 'Portero'), ('Defensa Central', 'Defensa Central'), ('Lateral Derecho', 'Lateral Derecho'), ('Lateral Izquierdo', 'Lateral Izquierdo'), ('Mediocampista Defensivo', 'Mediocampista Defensivo'), ('Mediocampista Ofensivo', 'Mediocampista Ofensivo'), ('Extremo Derecho', 'Extremo Derecho'), ('Extremo Izquierdo', 'Extremo Izquierdo'), ('Delantero Centro', 'Delantero Centro'), ('Segundo Delantero', 'Segundo Delantero')], max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
