# Generated by Django 5.1.1 on 2024-09-13 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo', '0001_initial'),
        ('posicion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='static/images/jugadores/')),
                ('fecha_nacimiento', models.DateField()),
                ('numero_camiseta', models.IntegerField()),
                ('es_titular', models.BooleanField(default=False)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo.equipo')),
                ('posicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posicion.posicion')),
            ],
        ),
    ]
