# Generated by Django 5.1.1 on 2024-09-13 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuerpoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='static/images/cuerpoTecnico/')),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=50)),
                ('rol', models.CharField(choices=[('Técnico', 'Técnico'), ('Asistente', 'Asistente'), ('Médico', 'Médico'), ('Preparador Físico', 'Preparador Físico')], max_length=20)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo.equipo')),
            ],
        ),
    ]
